
package br.com.correios.bsb.sigep.master.bean.cliente;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-22T13:52:10.733-03:00
 * Generated source version: 3.4.4
 *
 */
public final class AtendeCliente_AtendeClientePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClienteService");

    private AtendeCliente_AtendeClientePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AtendeClienteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AtendeClienteService ss = new AtendeClienteService(wsdlURL, SERVICE_NAME);
        AtendeCliente port = ss.getAtendeClientePort();

        {
        System.out.println("Invoking buscaServicosAdicionaisAtivos...");
        java.lang.String _buscaServicosAdicionaisAtivos_usuario = "_buscaServicosAdicionaisAtivos_usuario-1086808703";
        java.lang.String _buscaServicosAdicionaisAtivos_senha = "_buscaServicosAdicionaisAtivos_senha-562075745";
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalXML> _buscaServicosAdicionaisAtivos__return = port.buscaServicosAdicionaisAtivos(_buscaServicosAdicionaisAtivos_usuario, _buscaServicosAdicionaisAtivos_senha);
            System.out.println("buscaServicosAdicionaisAtivos.result=" + _buscaServicosAdicionaisAtivos__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking fechaPlp...");
        java.lang.String _fechaPlp_xml = "_fechaPlp_xml635969294";
        java.lang.Long _fechaPlp_idPlpCliente = Long.valueOf(-5327618150245460239l);
        java.lang.String _fechaPlp_cartaoPostagem = "_fechaPlp_cartaoPostagem-2030200859";
        java.lang.String _fechaPlp_faixaEtiquetas = "_fechaPlp_faixaEtiquetas1282976434";
        java.lang.String _fechaPlp_usuario = "_fechaPlp_usuario-1177083933";
        java.lang.String _fechaPlp_senha = "_fechaPlp_senha-441812399";
        try {
            java.lang.Long _fechaPlp__return = port.fechaPlp(_fechaPlp_xml, _fechaPlp_idPlpCliente, _fechaPlp_cartaoPostagem, _fechaPlp_faixaEtiquetas, _fechaPlp_usuario, _fechaPlp_senha);
            System.out.println("fechaPlp.result=" + _fechaPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validaPlp...");
        long _validaPlp_cliente = 1353700429982506548l;
        java.lang.String _validaPlp_numero = "_validaPlp_numero-2079820285";
        long _validaPlp_diretoria = -6843499962798429853l;
        java.lang.String _validaPlp_cartao = "_validaPlp_cartao832449747";
        java.lang.String _validaPlp_unidadePostagem = "_validaPlp_unidadePostagem-1811538407";
        java.lang.Long _validaPlp_servico = Long.valueOf(-2292725384093062331l);
        java.util.List<java.lang.String> _validaPlp_servicosAdicionais = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validaPlp_servicosAdicionaisVal1 = "_validaPlp_servicosAdicionaisVal1467082055";
        _validaPlp_servicosAdicionais.add(_validaPlp_servicosAdicionaisVal1);
        java.lang.String _validaPlp_usuario = "_validaPlp_usuario338263267";
        java.lang.String _validaPlp_senha = "_validaPlp_senha1794015579";
        try {
            boolean _validaPlp__return = port.validaPlp(_validaPlp_cliente, _validaPlp_numero, _validaPlp_diretoria, _validaPlp_cartao, _validaPlp_unidadePostagem, _validaPlp_servico, _validaPlp_servicosAdicionais, _validaPlp_usuario, _validaPlp_senha);
            System.out.println("validaPlp.result=" + _validaPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking calculaTarifaServico...");
        java.lang.String _calculaTarifaServico_codAdministrativo = "_calculaTarifaServico_codAdministrativo-1744297786";
        java.lang.String _calculaTarifaServico_usuario = "_calculaTarifaServico_usuario1370867493";
        java.lang.String _calculaTarifaServico_senha = "_calculaTarifaServico_senha1572057922";
        java.lang.String _calculaTarifaServico_codServico = "_calculaTarifaServico_codServico-1192498569";
        java.lang.String _calculaTarifaServico_cepOrigem = "_calculaTarifaServico_cepOrigem797526987";
        java.lang.String _calculaTarifaServico_cepDestino = "_calculaTarifaServico_cepDestino246139527";
        java.lang.String _calculaTarifaServico_peso = "_calculaTarifaServico_peso1888532236";
        java.lang.Integer _calculaTarifaServico_codFormato = Integer.valueOf(-210497984);
        java.lang.Double _calculaTarifaServico_comprimento = Double.valueOf(0.09670802207227591);
        java.lang.Double _calculaTarifaServico_altura = Double.valueOf(0.11698372148659397);
        java.lang.Double _calculaTarifaServico_largura = Double.valueOf(0.2659891638583345);
        java.lang.Double _calculaTarifaServico_diametro = Double.valueOf(0.9044132671093894);
        java.lang.String _calculaTarifaServico_codMaoPropria = "_calculaTarifaServico_codMaoPropria-788029008";
        java.lang.Double _calculaTarifaServico_valorDeclarado = Double.valueOf(0.22558294599680906);
        java.lang.String _calculaTarifaServico_codAvisoRecebimento = "_calculaTarifaServico_codAvisoRecebimento-117635015";
        try {
            java.lang.String _calculaTarifaServico__return = port.calculaTarifaServico(_calculaTarifaServico_codAdministrativo, _calculaTarifaServico_usuario, _calculaTarifaServico_senha, _calculaTarifaServico_codServico, _calculaTarifaServico_cepOrigem, _calculaTarifaServico_cepDestino, _calculaTarifaServico_peso, _calculaTarifaServico_codFormato, _calculaTarifaServico_comprimento, _calculaTarifaServico_altura, _calculaTarifaServico_largura, _calculaTarifaServico_diametro, _calculaTarifaServico_codMaoPropria, _calculaTarifaServico_valorDeclarado, _calculaTarifaServico_codAvisoRecebimento);
            System.out.println("calculaTarifaServico.result=" + _calculaTarifaServico__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaSeTodosObjetosCancelados...");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _verificaSeTodosObjetosCancelados_arg0 = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal _verificaSeTodosObjetosCancelados_arg0Val1 = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal();
        _verificaSeTodosObjetosCancelados_arg0Val1.setCodigoEtiqueta("CodigoEtiqueta153992206");
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.837-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataBloqueioObjeto(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.839-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataCancelamentoEtiqueta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.839-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.840-03:00"));
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK();
        _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK.setCodigoEtiqueta("CodigoEtiqueta1115737038");
        _verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK.setPlpNu(3579910883375480730l);
        _verificaSeTodosObjetosCancelados_arg0Val1.setObjetoPostalPK(_verificaSeTodosObjetosCancelados_arg0Val1ObjetoPostalPK);
        _verificaSeTodosObjetosCancelados_arg0Val1.setPlpNu(Long.valueOf(4512644845322392666l));
        br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem();
        br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setCodigoAdministrativo("CodigoAdministrativo671185250");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getContratos().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemContratos);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.841-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.841-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.841-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajAtualizacao(Integer.valueOf(141008860));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaFim(Integer.valueOf(-618097730));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaInicio(Integer.valueOf(-760215283));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoStatusCartao("DescricaoStatusCartao-1448441547");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica-1116129631");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setHorajAtualizacao(Integer.valueOf(-127812329));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setNumero("Numero128845951");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemServicos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getServicos().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemServicos);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setStatusCartaoPostagem("StatusCartaoPostagem-474106321");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setStatusCodigo("StatusCodigo1974289489");
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.setUnidadeGenerica("UnidadeGenerica-757345042");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem.getUnidadesPostagem().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setCartaoPostagem(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemCartaoPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemConteudoProibido = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setConteudoProibido(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemConteudoProibido);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.842-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataAtualizacaoSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.843-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataFechamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.843-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataPostagem(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.844-03:00"));
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setDataPostagemSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.844-03:00"));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemObjetosPostais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getObjetosPostais().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemObjetosPostais);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setPlpCliente(-8965583162574538654l);
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setPlpNu(1982880477152887568l);
        java.util.List<java.lang.Integer> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXml = new java.util.ArrayList<java.lang.Integer>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getPlpXml().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXml);
        java.util.List<java.lang.Integer> _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXmlRetorno = new java.util.ArrayList<java.lang.Integer>();
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.getPlpXmlRetorno().addAll(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemPlpXmlRetorno);
        br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemStatus = br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp.FECHADA;
        _verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem.setStatus(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagemStatus);
        _verificaSeTodosObjetosCancelados_arg0Val1.setPreListaPostagem(_verificaSeTodosObjetosCancelados_arg0Val1PreListaPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _verificaSeTodosObjetosCancelados_arg0Val1RestricaoAerea = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
        _verificaSeTodosObjetosCancelados_arg0Val1.setRestricaoAerea(_verificaSeTodosObjetosCancelados_arg0Val1RestricaoAerea);
        _verificaSeTodosObjetosCancelados_arg0Val1.setStatusBloqueio("StatusBloqueio-1915095526");
        br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal _verificaSeTodosObjetosCancelados_arg0Val1StatusEtiqueta = br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal.POSTADO;
        _verificaSeTodosObjetosCancelados_arg0Val1.setStatusEtiqueta(_verificaSeTodosObjetosCancelados_arg0Val1StatusEtiqueta);
        _verificaSeTodosObjetosCancelados_arg0.add(_verificaSeTodosObjetosCancelados_arg0Val1);
        try {
            boolean _verificaSeTodosObjetosCancelados__return = port.verificaSeTodosObjetosCancelados(_verificaSeTodosObjetosCancelados_arg0);
            System.out.println("verificaSeTodosObjetosCancelados.result=" + _verificaSeTodosObjetosCancelados__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cancelarObjeto...");
        java.lang.Long _cancelarObjeto_idPlp = Long.valueOf(-4640473692743586801l);
        java.lang.String _cancelarObjeto_numeroEtiqueta = "_cancelarObjeto_numeroEtiqueta-1238524751";
        java.lang.String _cancelarObjeto_usuario = "_cancelarObjeto_usuario-2051942585";
        java.lang.String _cancelarObjeto_senha = "_cancelarObjeto_senha248809205";
        try {
            java.lang.Boolean _cancelarObjeto__return = port.cancelarObjeto(_cancelarObjeto_idPlp, _cancelarObjeto_numeroEtiqueta, _cancelarObjeto_usuario, _cancelarObjeto_senha);
            System.out.println("cancelarObjeto.result=" + _cancelarObjeto__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarParametrosPorDescricao...");
        java.lang.String _pesquisarParametrosPorDescricao_prefix = "_pesquisarParametrosPorDescricao_prefix90025912";
        br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _pesquisarParametrosPorDescricao__return = port.pesquisarParametrosPorDescricao(_pesquisarParametrosPorDescricao_prefix);
        System.out.println("pesquisarParametrosPorDescricao.result=" + _pesquisarParametrosPorDescricao__return);


        }
        {
        System.out.println("Invoking atualizaPagamentoNaEntrega...");
        java.lang.String _atualizaPagamentoNaEntrega_usuario = "_atualizaPagamentoNaEntrega_usuario-1665956240";
        java.lang.String _atualizaPagamentoNaEntrega_senha = "_atualizaPagamentoNaEntrega_senha-1689690371";
        try {
            java.lang.String _atualizaPagamentoNaEntrega__return = port.atualizaPagamentoNaEntrega(_atualizaPagamentoNaEntrega_usuario, _atualizaPagamentoNaEntrega_senha);
            System.out.println("atualizaPagamentoNaEntrega.result=" + _atualizaPagamentoNaEntrega__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterClienteAtualizacao...");
        java.lang.String _obterClienteAtualizacao_cnpjCliente = "_obterClienteAtualizacao_cnpjCliente-929384958";
        java.lang.String _obterClienteAtualizacao_usuario = "_obterClienteAtualizacao_usuario-652509151";
        java.lang.String _obterClienteAtualizacao_senha = "_obterClienteAtualizacao_senha796659908";
        try {
            javax.xml.datatype.XMLGregorianCalendar _obterClienteAtualizacao__return = port.obterClienteAtualizacao(_obterClienteAtualizacao_cnpjCliente, _obterClienteAtualizacao_usuario, _obterClienteAtualizacao_senha);
            System.out.println("obterClienteAtualizacao.result=" + _obterClienteAtualizacao__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaDisponibilidadeServico...");
        java.lang.Integer _verificaDisponibilidadeServico_codAdministrativo = Integer.valueOf(1177451327);
        java.lang.String _verificaDisponibilidadeServico_numeroServico = "_verificaDisponibilidadeServico_numeroServico-252426929";
        java.lang.String _verificaDisponibilidadeServico_cepOrigem = "_verificaDisponibilidadeServico_cepOrigem320607416";
        java.lang.String _verificaDisponibilidadeServico_cepDestino = "_verificaDisponibilidadeServico_cepDestino303435859";
        java.lang.String _verificaDisponibilidadeServico_usuario = "_verificaDisponibilidadeServico_usuario-1416693365";
        java.lang.String _verificaDisponibilidadeServico_senha = "_verificaDisponibilidadeServico_senha1286105871";
        try {
            java.lang.String _verificaDisponibilidadeServico__return = port.verificaDisponibilidadeServico(_verificaDisponibilidadeServico_codAdministrativo, _verificaDisponibilidadeServico_numeroServico, _verificaDisponibilidadeServico_cepOrigem, _verificaDisponibilidadeServico_cepDestino, _verificaDisponibilidadeServico_usuario, _verificaDisponibilidadeServico_senha);
            System.out.println("verificaDisponibilidadeServico.result=" + _verificaDisponibilidadeServico__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking fechaPlpVariosServicos...");
        java.lang.String _fechaPlpVariosServicos_xml = "_fechaPlpVariosServicos_xml-1794306351";
        java.lang.Long _fechaPlpVariosServicos_idPlpCliente = Long.valueOf(-6006604047995846535l);
        java.lang.String _fechaPlpVariosServicos_cartaoPostagem = "_fechaPlpVariosServicos_cartaoPostagem585972952";
        java.util.List<java.lang.String> _fechaPlpVariosServicos_listaEtiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _fechaPlpVariosServicos_listaEtiquetasVal1 = "_fechaPlpVariosServicos_listaEtiquetasVal-374764634";
        _fechaPlpVariosServicos_listaEtiquetas.add(_fechaPlpVariosServicos_listaEtiquetasVal1);
        java.lang.String _fechaPlpVariosServicos_usuario = "_fechaPlpVariosServicos_usuario1626655704";
        java.lang.String _fechaPlpVariosServicos_senha = "_fechaPlpVariosServicos_senha1823513447";
        try {
            java.lang.Long _fechaPlpVariosServicos__return = port.fechaPlpVariosServicos(_fechaPlpVariosServicos_xml, _fechaPlpVariosServicos_idPlpCliente, _fechaPlpVariosServicos_cartaoPostagem, _fechaPlpVariosServicos_listaEtiquetas, _fechaPlpVariosServicos_usuario, _fechaPlpVariosServicos_senha);
            System.out.println("fechaPlpVariosServicos.result=" + _fechaPlpVariosServicos__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking geraDigitoVerificadorEtiquetas...");
        java.util.List<java.lang.String> _geraDigitoVerificadorEtiquetas_etiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _geraDigitoVerificadorEtiquetas_etiquetasVal1 = "_geraDigitoVerificadorEtiquetas_etiquetasVal-491668365";
        _geraDigitoVerificadorEtiquetas_etiquetas.add(_geraDigitoVerificadorEtiquetas_etiquetasVal1);
        java.lang.String _geraDigitoVerificadorEtiquetas_usuario = "_geraDigitoVerificadorEtiquetas_usuario-667413857";
        java.lang.String _geraDigitoVerificadorEtiquetas_senha = "_geraDigitoVerificadorEtiquetas_senha434163096";
        try {
            java.util.List<java.lang.Integer> _geraDigitoVerificadorEtiquetas__return = port.geraDigitoVerificadorEtiquetas(_geraDigitoVerificadorEtiquetas_etiquetas, _geraDigitoVerificadorEtiquetas_usuario, _geraDigitoVerificadorEtiquetas_senha);
            System.out.println("geraDigitoVerificadorEtiquetas.result=" + _geraDigitoVerificadorEtiquetas__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterEmbalagemLRS...");
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.EmbalagemLRSMaster> _obterEmbalagemLRS__return = port.obterEmbalagemLRS();
            System.out.println("obterEmbalagemLRS.result=" + _obterEmbalagemLRS__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validaEtiquetaPLP...");
        java.lang.String _validaEtiquetaPLP_numeroEtiqueta = "_validaEtiquetaPLP_numeroEtiqueta1393007704";
        java.lang.Long _validaEtiquetaPLP_idPlp = Long.valueOf(6321749802266829780l);
        java.lang.String _validaEtiquetaPLP_usuario = "_validaEtiquetaPLP_usuario-1826283188";
        java.lang.String _validaEtiquetaPLP_senha = "_validaEtiquetaPLP_senha-976603111";
        try {
            boolean _validaEtiquetaPLP__return = port.validaEtiquetaPLP(_validaEtiquetaPLP_numeroEtiqueta, _validaEtiquetaPLP_idPlp, _validaEtiquetaPLP_usuario, _validaEtiquetaPLP_senha);
            System.out.println("validaEtiquetaPLP.result=" + _validaEtiquetaPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaServicosValorDeclarado...");
        java.lang.String _buscaServicosValorDeclarado_usuario = "_buscaServicosValorDeclarado_usuario2110610184";
        java.lang.String _buscaServicosValorDeclarado_senha = "_buscaServicosValorDeclarado_senha627223247";
        try {
            java.util.List<java.lang.String> _buscaServicosValorDeclarado__return = port.buscaServicosValorDeclarado(_buscaServicosValorDeclarado_usuario, _buscaServicosValorDeclarado_senha);
            System.out.println("buscaServicosValorDeclarado.result=" + _buscaServicosValorDeclarado__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking consultaCEP...");
        java.lang.String _consultaCEP_cep = "_consultaCEP_cep-851127410";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP _consultaCEP__return = port.consultaCEP(_consultaCEP_cep);
            System.out.println("consultaCEP.result=" + _consultaCEP__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking integrarUsuarioScol...");
        java.lang.Integer _integrarUsuarioScol_codAdministrativo = Integer.valueOf(-1928167259);
        java.lang.String _integrarUsuarioScol_usuario = "_integrarUsuarioScol_usuario2090952596";
        java.lang.String _integrarUsuarioScol_senha = "_integrarUsuarioScol_senha-279783018";
        try {
            java.lang.Boolean _integrarUsuarioScol__return = port.integrarUsuarioScol(_integrarUsuarioScol_codAdministrativo, _integrarUsuarioScol_usuario, _integrarUsuarioScol_senha);
            System.out.println("integrarUsuarioScol.result=" + _integrarUsuarioScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarDimensoesServico...");
        java.lang.String _pesquisarDimensoesServico_codigo = "_pesquisarDimensoesServico_codigo-451347540";
        java.lang.String _pesquisarDimensoesServico_embalagem = "_pesquisarDimensoesServico_embalagem1576608202";
        br.com.correios.bsb.sigep.master.bean.cliente.DimensaoTO _pesquisarDimensoesServico__return = port.pesquisarDimensoesServico(_pesquisarDimensoesServico_codigo, _pesquisarDimensoesServico_embalagem);
        System.out.println("pesquisarDimensoesServico.result=" + _pesquisarDimensoesServico__return);


        }
        {
        System.out.println("Invoking pesquisarEmbalagensPorServico...");
        java.lang.String _pesquisarEmbalagensPorServico_codigo = "_pesquisarEmbalagensPorServico_codigo-2082563202";
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.TipoEmbalagem> _pesquisarEmbalagensPorServico__return = port.pesquisarEmbalagensPorServico(_pesquisarEmbalagensPorServico_codigo);
        System.out.println("pesquisarEmbalagensPorServico.result=" + _pesquisarEmbalagensPorServico__return);


        }
        {
        System.out.println("Invoking atualizaRemessaAgrupada...");
        java.lang.String _atualizaRemessaAgrupada_usuario = "_atualizaRemessaAgrupada_usuario-1693110297";
        java.lang.String _atualizaRemessaAgrupada_senha = "_atualizaRemessaAgrupada_senha-1330058341";
        try {
            java.lang.String _atualizaRemessaAgrupada__return = port.atualizaRemessaAgrupada(_atualizaRemessaAgrupada_usuario, _atualizaRemessaAgrupada_senha);
            System.out.println("atualizaRemessaAgrupada.result=" + _atualizaRemessaAgrupada__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaPLP...");
        java.lang.Long _solicitaPLP_idPlpMaster = Long.valueOf(1258479065152923079l);
        java.lang.String _solicitaPLP_numEtiqueta = "_solicitaPLP_numEtiqueta1302049477";
        java.lang.String _solicitaPLP_usuario = "_solicitaPLP_usuario-23008469";
        java.lang.String _solicitaPLP_senha = "_solicitaPLP_senha244168";
        try {
            java.lang.String _solicitaPLP__return = port.solicitaPLP(_solicitaPLP_idPlpMaster, _solicitaPLP_numEtiqueta, _solicitaPLP_usuario, _solicitaPLP_senha);
            System.out.println("solicitaPLP.result=" + _solicitaPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getStatusCartaoPostagem...");
        java.lang.String _getStatusCartaoPostagem_numeroCartaoPostagem = "_getStatusCartaoPostagem_numeroCartaoPostagem-1701929766";
        java.lang.String _getStatusCartaoPostagem_usuario = "_getStatusCartaoPostagem_usuario-1874421709";
        java.lang.String _getStatusCartaoPostagem_senha = "_getStatusCartaoPostagem_senha2142040700";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusCartao _getStatusCartaoPostagem__return = port.getStatusCartaoPostagem(_getStatusCartaoPostagem_numeroCartaoPostagem, _getStatusCartaoPostagem_usuario, _getStatusCartaoPostagem_senha);
            System.out.println("getStatusCartaoPostagem.result=" + _getStatusCartaoPostagem__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking verificaModalTransporte...");
        java.lang.String _verificaModalTransporte_codigoServico = "_verificaModalTransporte_codigoServico1607146140";
        java.lang.String _verificaModalTransporte_cepOrigem = "_verificaModalTransporte_cepOrigem-743309273";
        java.lang.String _verificaModalTransporte_cepDestino = "_verificaModalTransporte_cepDestino-1569526977";
        java.lang.String _verificaModalTransporte_usuario = "_verificaModalTransporte_usuario1407195056";
        java.lang.String _verificaModalTransporte_senha = "_verificaModalTransporte_senha-1676234491";
        try {
            java.lang.String _verificaModalTransporte__return = port.verificaModalTransporte(_verificaModalTransporte_codigoServico, _verificaModalTransporte_cepOrigem, _verificaModalTransporte_cepDestino, _verificaModalTransporte_usuario, _verificaModalTransporte_senha);
            System.out.println("verificaModalTransporte.result=" + _verificaModalTransporte__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaDataAtual...");
        javax.xml.datatype.XMLGregorianCalendar _buscaDataAtual__return = port.buscaDataAtual();
        System.out.println("buscaDataAtual.result=" + _buscaDataAtual__return);


        }
        {
        System.out.println("Invoking buscaTarifaVale...");
        java.lang.String _buscaTarifaVale_codAdministrativo = "_buscaTarifaVale_codAdministrativo-489439502";
        java.lang.String _buscaTarifaVale_usuario = "_buscaTarifaVale_usuario-545199039";
        java.lang.String _buscaTarifaVale_senha = "_buscaTarifaVale_senha-330783775";
        java.lang.String _buscaTarifaVale_codServico = "_buscaTarifaVale_codServico1462623818";
        java.lang.String _buscaTarifaVale_cepOrigem = "_buscaTarifaVale_cepOrigem-554280857";
        java.lang.String _buscaTarifaVale_cepDestino = "_buscaTarifaVale_cepDestino178893156";
        java.lang.String _buscaTarifaVale_peso = "_buscaTarifaVale_peso-1260649643";
        java.lang.Integer _buscaTarifaVale_codFormato = Integer.valueOf(-558245735);
        java.lang.Double _buscaTarifaVale_comprimento = Double.valueOf(0.40822463584113267);
        java.lang.Double _buscaTarifaVale_altura = Double.valueOf(0.4341586145985511);
        java.lang.Double _buscaTarifaVale_largura = Double.valueOf(0.018374967384931384);
        java.lang.Double _buscaTarifaVale_valorDeclarado = Double.valueOf(0.7082841893640098);
        java.lang.String _buscaTarifaVale_servicoAdicional = "_buscaTarifaVale_servicoAdicional10100697";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ValePostal _buscaTarifaVale__return = port.buscaTarifaVale(_buscaTarifaVale_codAdministrativo, _buscaTarifaVale_usuario, _buscaTarifaVale_senha, _buscaTarifaVale_codServico, _buscaTarifaVale_cepOrigem, _buscaTarifaVale_cepDestino, _buscaTarifaVale_peso, _buscaTarifaVale_codFormato, _buscaTarifaVale_comprimento, _buscaTarifaVale_altura, _buscaTarifaVale_largura, _buscaTarifaVale_valorDeclarado, _buscaTarifaVale_servicoAdicional);
            System.out.println("buscaTarifaVale.result=" + _buscaTarifaVale__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validarPostagemSimultanea...");
        java.lang.Integer _validarPostagemSimultanea_codAdministrativo = Integer.valueOf(67829814);
        java.lang.Integer _validarPostagemSimultanea_codigoServico = Integer.valueOf(467181248);
        java.lang.String _validarPostagemSimultanea_idCartaoPostagem = "_validarPostagemSimultanea_idCartaoPostagem297022790";
        java.lang.String _validarPostagemSimultanea_cepDestinatario = "_validarPostagemSimultanea_cepDestinatario-390016334";
        br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea _validarPostagemSimultanea_coleta = new br.com.correios.bsb.sigep.master.bean.cliente.ColetaSimultanea();
        _validarPostagemSimultanea_coleta.setCklist("Cklist-1245792309");
        _validarPostagemSimultanea_coleta.setDescricao("Descricao1639785071");
        java.util.List<java.lang.String> _validarPostagemSimultanea_coletaDocumento = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validarPostagemSimultanea_coletaDocumentoVal1 = "_validarPostagemSimultanea_coletaDocumentoVal724136141";
        _validarPostagemSimultanea_coletaDocumento.add(_validarPostagemSimultanea_coletaDocumentoVal1);
        _validarPostagemSimultanea_coleta.getDocumento().addAll(_validarPostagemSimultanea_coletaDocumento);
        _validarPostagemSimultanea_coleta.setIdCliente("IdCliente-1369576195");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Produto> _validarPostagemSimultanea_coletaProduto = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Produto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Produto _validarPostagemSimultanea_coletaProdutoVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Produto();
        _validarPostagemSimultanea_coletaProdutoVal1.setCodigo("Codigo1607410959");
        _validarPostagemSimultanea_coletaProdutoVal1.setQtd("Qtd333482207");
        _validarPostagemSimultanea_coletaProdutoVal1.setTipo("Tipo-1235310993");
        _validarPostagemSimultanea_coletaProduto.add(_validarPostagemSimultanea_coletaProdutoVal1);
        _validarPostagemSimultanea_coleta.getProduto().addAll(_validarPostagemSimultanea_coletaProduto);
        br.com.correios.bsb.sigep.master.bean.cliente.Remetente _validarPostagemSimultanea_coletaRemetente = new br.com.correios.bsb.sigep.master.bean.cliente.Remetente();
        _validarPostagemSimultanea_coletaRemetente.setBairro("Bairro-544060157");
        _validarPostagemSimultanea_coletaRemetente.setCep("Cep-852454942");
        _validarPostagemSimultanea_coletaRemetente.setCidade("Cidade-1447799907");
        _validarPostagemSimultanea_coletaRemetente.setComplemento("Complemento2128238797");
        _validarPostagemSimultanea_coletaRemetente.setDdd("Ddd-330361725");
        _validarPostagemSimultanea_coletaRemetente.setEmail("Email683038863");
        _validarPostagemSimultanea_coletaRemetente.setLogradouro("Logradouro414204877");
        _validarPostagemSimultanea_coletaRemetente.setNome("Nome-1629683345");
        _validarPostagemSimultanea_coletaRemetente.setNumero("Numero1699308227");
        _validarPostagemSimultanea_coletaRemetente.setReferencia("Referencia-1502144942");
        _validarPostagemSimultanea_coletaRemetente.setTelefone("Telefone51278942");
        _validarPostagemSimultanea_coletaRemetente.setUf("Uf-1527582492");
        _validarPostagemSimultanea_coletaRemetente.setCelular("Celular-475587608");
        _validarPostagemSimultanea_coletaRemetente.setDddCelular("DddCelular-52231654");
        _validarPostagemSimultanea_coletaRemetente.setIdentificacao("Identificacao1290953599");
        _validarPostagemSimultanea_coletaRemetente.setSms("Sms1996590381");
        _validarPostagemSimultanea_coleta.setRemetente(_validarPostagemSimultanea_coletaRemetente);
        _validarPostagemSimultanea_coleta.setTipo("Tipo-673164921");
        _validarPostagemSimultanea_coleta.setValorDeclarado("ValorDeclarado-1088263281");
        _validarPostagemSimultanea_coleta.setObj("Obj208838480");
        _validarPostagemSimultanea_coleta.setObs("Obs-2055237029");
        java.lang.String _validarPostagemSimultanea_usuario = "_validarPostagemSimultanea_usuario-1309269893";
        java.lang.String _validarPostagemSimultanea_senha = "_validarPostagemSimultanea_senha523150933";
        try {
            java.lang.Boolean _validarPostagemSimultanea__return = port.validarPostagemSimultanea(_validarPostagemSimultanea_codAdministrativo, _validarPostagemSimultanea_codigoServico, _validarPostagemSimultanea_idCartaoPostagem, _validarPostagemSimultanea_cepDestinatario, _validarPostagemSimultanea_coleta, _validarPostagemSimultanea_usuario, _validarPostagemSimultanea_senha);
            System.out.println("validarPostagemSimultanea.result=" + _validarPostagemSimultanea__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getStatusPLP...");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _getStatusPLP_arg0 = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal _getStatusPLP_arg0Val1 = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal();
        _getStatusPLP_arg0Val1.setCodigoEtiqueta("CodigoEtiqueta1816398300");
        _getStatusPLP_arg0Val1.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.875-03:00"));
        _getStatusPLP_arg0Val1.setDataBloqueioObjeto(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.875-03:00"));
        _getStatusPLP_arg0Val1.setDataCancelamentoEtiqueta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.877-03:00"));
        _getStatusPLP_arg0Val1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.878-03:00"));
        br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK _getStatusPLP_arg0Val1ObjetoPostalPK = new br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostalPK();
        _getStatusPLP_arg0Val1ObjetoPostalPK.setCodigoEtiqueta("CodigoEtiqueta1784559991");
        _getStatusPLP_arg0Val1ObjetoPostalPK.setPlpNu(-7649056137715128942l);
        _getStatusPLP_arg0Val1.setObjetoPostalPK(_getStatusPLP_arg0Val1ObjetoPostalPK);
        _getStatusPLP_arg0Val1.setPlpNu(Long.valueOf(7007856410337962401l));
        br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem _getStatusPLP_arg0Val1PreListaPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.PreListaPostagem();
        br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem = new br.com.correios.bsb.sigep.master.bean.cliente.CartaoPostagemERP();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setCodigoAdministrativo("CodigoAdministrativo1508277728");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getContratos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.879-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.879-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.881-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajAtualizacao(Integer.valueOf(1074711469));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaFim(Integer.valueOf(-1611321021));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaInicio(Integer.valueOf(722687867));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoStatusCartao("DescricaoStatusCartao-1274739627");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica1500557913");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setHorajAtualizacao(Integer.valueOf(1677512392));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setNumero("Numero-1890961721");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getServicos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCartaoPostagem("StatusCartaoPostagem-513882994");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCodigo("StatusCodigo327282385");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setUnidadeGenerica("UnidadeGenerica-1634220284");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.UnidadePostagemERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getUnidadesPostagem().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem);
        _getStatusPLP_arg0Val1PreListaPostagem.setCartaoPostagem(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _getStatusPLP_arg0Val1PreListaPostagemConteudoProibido = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.S;
        _getStatusPLP_arg0Val1PreListaPostagem.setConteudoProibido(_getStatusPLP_arg0Val1PreListaPostagemConteudoProibido);
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.883-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.885-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataFechamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.885-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagem(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.886-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagemSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-09-22T13:52:10.886-03:00"));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal> _getStatusPLP_arg0Val1PreListaPostagemObjetosPostais = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.ObjetoPostal>();
        _getStatusPLP_arg0Val1PreListaPostagem.getObjetosPostais().addAll(_getStatusPLP_arg0Val1PreListaPostagemObjetosPostais);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpCliente(8520690571179824740l);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpNu(9197336217327345155l);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXml = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXml().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXml);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXmlRetorno().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno);
        br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _getStatusPLP_arg0Val1PreListaPostagemStatus = br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp.FECHADA;
        _getStatusPLP_arg0Val1PreListaPostagem.setStatus(_getStatusPLP_arg0Val1PreListaPostagemStatus);
        _getStatusPLP_arg0Val1.setPreListaPostagem(_getStatusPLP_arg0Val1PreListaPostagem);
        br.com.correios.bsb.sigep.master.bean.cliente.SimNao _getStatusPLP_arg0Val1RestricaoAerea = br.com.correios.bsb.sigep.master.bean.cliente.SimNao.N;
        _getStatusPLP_arg0Val1.setRestricaoAerea(_getStatusPLP_arg0Val1RestricaoAerea);
        _getStatusPLP_arg0Val1.setStatusBloqueio("StatusBloqueio-211315230");
        br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal _getStatusPLP_arg0Val1StatusEtiqueta = br.com.correios.bsb.sigep.master.bean.cliente.StatusObjetoPostal.CANCELADO;
        _getStatusPLP_arg0Val1.setStatusEtiqueta(_getStatusPLP_arg0Val1StatusEtiqueta);
        _getStatusPLP_arg0.add(_getStatusPLP_arg0Val1);
        java.lang.String _getStatusPLP_arg1 = "_getStatusPLP_arg1-1741251414";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.StatusPlp _getStatusPLP__return = port.getStatusPLP(_getStatusPLP_arg0, _getStatusPLP_arg1);
            System.out.println("getStatusPLP.result=" + _getStatusPLP__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking pesquisarServicosAdicionais...");
        java.lang.String _pesquisarServicosAdicionais_codigo = "_pesquisarServicosAdicionais_codigo-1894926022";
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoAdicionalTO> _pesquisarServicosAdicionais__return = port.pesquisarServicosAdicionais(_pesquisarServicosAdicionais_codigo);
        System.out.println("pesquisarServicosAdicionais.result=" + _pesquisarServicosAdicionais__return);


        }
        {
        System.out.println("Invoking buscaServicosXServicosAdicionais...");
        java.lang.String _buscaServicosXServicosAdicionais_usuario = "_buscaServicosXServicosAdicionais_usuario1134029833";
        java.lang.String _buscaServicosXServicosAdicionais_senha = "_buscaServicosXServicosAdicionais_senha-365164495";
        try {
            java.util.List<java.lang.String> _buscaServicosXServicosAdicionais__return = port.buscaServicosXServicosAdicionais(_buscaServicosXServicosAdicionais_usuario, _buscaServicosXServicosAdicionais_senha);
            System.out.println("buscaServicosXServicosAdicionais.result=" + _buscaServicosXServicosAdicionais__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cancelarPedidoScol...");
        java.lang.String _cancelarPedidoScol_codAdministrativo = "_cancelarPedidoScol_codAdministrativo-635547958";
        java.lang.String _cancelarPedidoScol_idPostagem = "_cancelarPedidoScol_idPostagem375266188";
        java.lang.String _cancelarPedidoScol_tipo = "_cancelarPedidoScol_tipo567607447";
        java.lang.String _cancelarPedidoScol_usuario = "_cancelarPedidoScol_usuario238886694";
        java.lang.String _cancelarPedidoScol_senha = "_cancelarPedidoScol_senha1016714626";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.RetornoCancelamento _cancelarPedidoScol__return = port.cancelarPedidoScol(_cancelarPedidoScol_codAdministrativo, _cancelarPedidoScol_idPostagem, _cancelarPedidoScol_tipo, _cancelarPedidoScol_usuario, _cancelarPedidoScol_senha);
            System.out.println("cancelarPedidoScol.result=" + _cancelarPedidoScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking bloquearObjeto...");
        java.lang.String _bloquearObjeto_numeroEtiqueta = "_bloquearObjeto_numeroEtiqueta-110722590";
        java.lang.Long _bloquearObjeto_idPlp = Long.valueOf(-3959047962943876275l);
        br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio _bloquearObjeto_tipoBloqueio = br.com.correios.bsb.sigep.master.bean.cliente.TipoBloqueio.EXTRAVIO_VAREJO_POS_INDENIZADO;
        br.com.correios.bsb.sigep.master.bean.cliente.Acao _bloquearObjeto_acao = br.com.correios.bsb.sigep.master.bean.cliente.Acao.DEVOLVIDO_AO_REMETENTE;
        java.lang.String _bloquearObjeto_usuario = "_bloquearObjeto_usuario-658731952";
        java.lang.String _bloquearObjeto_senha = "_bloquearObjeto_senha-597588665";
        try {
            java.lang.String _bloquearObjeto__return = port.bloquearObjeto(_bloquearObjeto_numeroEtiqueta, _bloquearObjeto_idPlp, _bloquearObjeto_tipoBloqueio, _bloquearObjeto_acao, _bloquearObjeto_usuario, _bloquearObjeto_senha);
            System.out.println("bloquearObjeto.result=" + _bloquearObjeto__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaContrato...");
        java.lang.String _buscaContrato_numero = "_buscaContrato_numero172727043";
        long _buscaContrato_diretoria = -1370638645221684135l;
        java.lang.String _buscaContrato_usuario = "_buscaContrato_usuario-1086352646";
        java.lang.String _buscaContrato_senha = "_buscaContrato_senha1235069564";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ContratoERP _buscaContrato__return = port.buscaContrato(_buscaContrato_numero, _buscaContrato_diretoria, _buscaContrato_usuario, _buscaContrato_senha);
            System.out.println("buscaContrato.result=" + _buscaContrato__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaEtiquetas...");
        java.lang.String _solicitaEtiquetas_tipoDestinatario = "_solicitaEtiquetas_tipoDestinatario-237860273";
        java.lang.String _solicitaEtiquetas_identificador = "_solicitaEtiquetas_identificador-1877656787";
        java.lang.Long _solicitaEtiquetas_idServico = Long.valueOf(7621851366925603536l);
        java.lang.Integer _solicitaEtiquetas_qtdEtiquetas = Integer.valueOf(-2072675996);
        java.lang.String _solicitaEtiquetas_usuario = "_solicitaEtiquetas_usuario-33331185";
        java.lang.String _solicitaEtiquetas_senha = "_solicitaEtiquetas_senha-1767038722";
        try {
            java.lang.String _solicitaEtiquetas__return = port.solicitaEtiquetas(_solicitaEtiquetas_tipoDestinatario, _solicitaEtiquetas_identificador, _solicitaEtiquetas_idServico, _solicitaEtiquetas_qtdEtiquetas, _solicitaEtiquetas_usuario, _solicitaEtiquetas_senha);
            System.out.println("solicitaEtiquetas.result=" + _solicitaEtiquetas__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitaXmlPlp...");
        java.lang.Long _solicitaXmlPlp_idPlpMaster = Long.valueOf(-413215604283123972l);
        java.lang.String _solicitaXmlPlp_usuario = "_solicitaXmlPlp_usuario-1155549501";
        java.lang.String _solicitaXmlPlp_senha = "_solicitaXmlPlp_senha957517736";
        try {
            java.lang.String _solicitaXmlPlp__return = port.solicitaXmlPlp(_solicitaXmlPlp_idPlpMaster, _solicitaXmlPlp_usuario, _solicitaXmlPlp_senha);
            System.out.println("solicitaXmlPlp.result=" + _solicitaXmlPlp__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validarPostagemReversa...");
        java.lang.String _validarPostagemReversa_codAdministrativo = "_validarPostagemReversa_codAdministrativo-882927330";
        java.lang.String _validarPostagemReversa_codigoServico = "_validarPostagemReversa_codigoServico408114276";
        java.lang.String _validarPostagemReversa_cepDestinatario = "_validarPostagemReversa_cepDestinatario2027102268";
        java.lang.String _validarPostagemReversa_idCartaoPostagem = "_validarPostagemReversa_idCartaoPostagem1122975172";
        br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa _validarPostagemReversa_coleta = new br.com.correios.bsb.sigep.master.bean.cliente.ColetaReversa();
        _validarPostagemReversa_coleta.setCklist("Cklist-2009386960");
        _validarPostagemReversa_coleta.setDescricao("Descricao-241853149");
        java.util.List<java.lang.String> _validarPostagemReversa_coletaDocumento = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validarPostagemReversa_coletaDocumentoVal1 = "_validarPostagemReversa_coletaDocumentoVal811616921";
        _validarPostagemReversa_coletaDocumento.add(_validarPostagemReversa_coletaDocumentoVal1);
        _validarPostagemReversa_coleta.getDocumento().addAll(_validarPostagemReversa_coletaDocumento);
        _validarPostagemReversa_coleta.setIdCliente("IdCliente-1188374308");
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Produto> _validarPostagemReversa_coletaProduto = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Produto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Produto _validarPostagemReversa_coletaProdutoVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Produto();
        _validarPostagemReversa_coletaProdutoVal1.setCodigo("Codigo773160759");
        _validarPostagemReversa_coletaProdutoVal1.setQtd("Qtd1869108867");
        _validarPostagemReversa_coletaProdutoVal1.setTipo("Tipo691989586");
        _validarPostagemReversa_coletaProduto.add(_validarPostagemReversa_coletaProdutoVal1);
        _validarPostagemReversa_coleta.getProduto().addAll(_validarPostagemReversa_coletaProduto);
        br.com.correios.bsb.sigep.master.bean.cliente.Remetente _validarPostagemReversa_coletaRemetente = new br.com.correios.bsb.sigep.master.bean.cliente.Remetente();
        _validarPostagemReversa_coletaRemetente.setBairro("Bairro261488856");
        _validarPostagemReversa_coletaRemetente.setCep("Cep734826375");
        _validarPostagemReversa_coletaRemetente.setCidade("Cidade-2143710384");
        _validarPostagemReversa_coletaRemetente.setComplemento("Complemento-2014466386");
        _validarPostagemReversa_coletaRemetente.setDdd("Ddd-458495140");
        _validarPostagemReversa_coletaRemetente.setEmail("Email-1538516489");
        _validarPostagemReversa_coletaRemetente.setLogradouro("Logradouro681590751");
        _validarPostagemReversa_coletaRemetente.setNome("Nome-2066005128");
        _validarPostagemReversa_coletaRemetente.setNumero("Numero-431990417");
        _validarPostagemReversa_coletaRemetente.setReferencia("Referencia-1031768652");
        _validarPostagemReversa_coletaRemetente.setTelefone("Telefone-2016523695");
        _validarPostagemReversa_coletaRemetente.setUf("Uf-136404495");
        _validarPostagemReversa_coletaRemetente.setCelular("Celular56935260");
        _validarPostagemReversa_coletaRemetente.setDddCelular("DddCelular193536082");
        _validarPostagemReversa_coletaRemetente.setIdentificacao("Identificacao130452249");
        _validarPostagemReversa_coletaRemetente.setSms("Sms532782856");
        _validarPostagemReversa_coleta.setRemetente(_validarPostagemReversa_coletaRemetente);
        _validarPostagemReversa_coleta.setTipo("Tipo1327095516");
        _validarPostagemReversa_coleta.setValorDeclarado("ValorDeclarado1141060387");
        _validarPostagemReversa_coleta.setAg("Ag-454413894");
        _validarPostagemReversa_coleta.setAr(Integer.valueOf(-1512024888));
        _validarPostagemReversa_coleta.setCartao("Cartao-1190075532");
        _validarPostagemReversa_coleta.setNumero(Integer.valueOf(-2114627124));
        java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.Objeto> _validarPostagemReversa_coletaObjCol = new java.util.ArrayList<br.com.correios.bsb.sigep.master.bean.cliente.Objeto>();
        br.com.correios.bsb.sigep.master.bean.cliente.Objeto _validarPostagemReversa_coletaObjColVal1 = new br.com.correios.bsb.sigep.master.bean.cliente.Objeto();
        _validarPostagemReversa_coletaObjColVal1.setDesc("Desc2003417557");
        _validarPostagemReversa_coletaObjColVal1.setEntrega("Entrega-1223488239");
        _validarPostagemReversa_coletaObjColVal1.setId("Id1209151772");
        _validarPostagemReversa_coletaObjColVal1.setItem("Item460070421");
        _validarPostagemReversa_coletaObjColVal1.setNum("Num-144593822");
        _validarPostagemReversa_coletaObjCol.add(_validarPostagemReversa_coletaObjColVal1);
        _validarPostagemReversa_coleta.getObjCol().addAll(_validarPostagemReversa_coletaObjCol);
        _validarPostagemReversa_coleta.setServicoAdicional("ServicoAdicional2084545418");
        java.lang.String _validarPostagemReversa_usuario = "_validarPostagemReversa_usuario-220906207";
        java.lang.String _validarPostagemReversa_senha = "_validarPostagemReversa_senha326016255";
        try {
            java.lang.Boolean _validarPostagemReversa__return = port.validarPostagemReversa(_validarPostagemReversa_codAdministrativo, _validarPostagemReversa_codigoServico, _validarPostagemReversa_cepDestinatario, _validarPostagemReversa_idCartaoPostagem, _validarPostagemReversa_coleta, _validarPostagemReversa_usuario, _validarPostagemReversa_senha);
            System.out.println("validarPostagemReversa.result=" + _validarPostagemReversa__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaCliente...");
        java.lang.String _buscaCliente_idContrato = "_buscaCliente_idContrato36417853";
        java.lang.String _buscaCliente_idCartaoPostagem = "_buscaCliente_idCartaoPostagem1363841750";
        java.lang.String _buscaCliente_usuario = "_buscaCliente_usuario-630199989";
        java.lang.String _buscaCliente_senha = "_buscaCliente_senha-1864304357";
        try {
            br.com.correios.bsb.sigep.master.bean.cliente.ClienteERP _buscaCliente__return = port.buscaCliente(_buscaCliente_idContrato, _buscaCliente_idCartaoPostagem, _buscaCliente_usuario, _buscaCliente_senha);
            System.out.println("buscaCliente.result=" + _buscaCliente__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaPagamentoEntrega...");
        java.lang.String _buscaPagamentoEntrega_usuario = "_buscaPagamentoEntrega_usuario-386878236";
        java.lang.String _buscaPagamentoEntrega_senha = "_buscaPagamentoEntrega_senha1341071621";
        java.lang.String _buscaPagamentoEntrega_contrato = "_buscaPagamentoEntrega_contrato859941186";
        java.lang.String _buscaPagamentoEntrega_dataInicio = "_buscaPagamentoEntrega_dataInicio2120949273";
        java.lang.String _buscaPagamentoEntrega_dataFim = "_buscaPagamentoEntrega_dataFim-1106172289";
        java.lang.String _buscaPagamentoEntrega_etiqueta = "_buscaPagamentoEntrega_etiqueta1351180108";
        try {
            java.lang.String _buscaPagamentoEntrega__return = port.buscaPagamentoEntrega(_buscaPagamentoEntrega_usuario, _buscaPagamentoEntrega_senha, _buscaPagamentoEntrega_contrato, _buscaPagamentoEntrega_dataInicio, _buscaPagamentoEntrega_dataFim, _buscaPagamentoEntrega_etiqueta);
            System.out.println("buscaPagamentoEntrega.result=" + _buscaPagamentoEntrega__return);

        } catch (ErroMontagemRelatorio_Exception e) {
            System.out.println("Expected exception: ErroMontagemRelatorio has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking solicitarPostagemScol...");
        java.lang.Integer _solicitarPostagemScol_codAdministrativo = Integer.valueOf(-392095187);
        java.lang.String _solicitarPostagemScol_xml = "_solicitarPostagemScol_xml886024607";
        java.lang.String _solicitarPostagemScol_usuario = "_solicitarPostagemScol_usuario1824821792";
        java.lang.String _solicitarPostagemScol_senha = "_solicitarPostagemScol_senha-1940655880";
        try {
            java.lang.String _solicitarPostagemScol__return = port.solicitarPostagemScol(_solicitarPostagemScol_codAdministrativo, _solicitarPostagemScol_xml, _solicitarPostagemScol_usuario, _solicitarPostagemScol_senha);
            System.out.println("solicitarPostagemScol.result=" + _solicitarPostagemScol__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking buscaServicos...");
        java.lang.String _buscaServicos_idContrato = "_buscaServicos_idContrato853078171";
        java.lang.String _buscaServicos_idCartaoPostagem = "_buscaServicos_idCartaoPostagem-1685582501";
        java.lang.String _buscaServicos_usuario = "_buscaServicos_usuario-1532880054";
        java.lang.String _buscaServicos_senha = "_buscaServicos_senha-297349728";
        try {
            java.util.List<br.com.correios.bsb.sigep.master.bean.cliente.ServicoERP> _buscaServicos__return = port.buscaServicos(_buscaServicos_idContrato, _buscaServicos_idCartaoPostagem, _buscaServicos_usuario, _buscaServicos_senha);
            System.out.println("buscaServicos.result=" + _buscaServicos__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) {
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking obterMensagemParametrizada...");
        java.lang.Short _obterMensagemParametrizada_id = Short.valueOf((short)24742);
        br.com.correios.bsb.sigep.master.bean.cliente.MensagemParametrizadaTO _obterMensagemParametrizada__return = port.obterMensagemParametrizada(_obterMensagemParametrizada_id);
        System.out.println("obterMensagemParametrizada.result=" + _obterMensagemParametrizada__return);


        }
        {
        System.out.println("Invoking buscaOpcoes...");
        java.util.List<java.lang.String> _buscaOpcoes_listaObjetos = new java.util.ArrayList<java.lang.String>();
        java.lang.String _buscaOpcoes_listaObjetosVal1 = "_buscaOpcoes_listaObjetosVal1798848091";
        _buscaOpcoes_listaObjetos.add(_buscaOpcoes_listaObjetosVal1);
        java.lang.String _buscaOpcoes_tipoResultado = "_buscaOpcoes_tipoResultado-1915249737";
        java.lang.String _buscaOpcoes_usuario = "_buscaOpcoes_usuario-1461488998";
        java.lang.String _buscaOpcoes_senha = "_buscaOpcoes_senha-916364203";
        try {
            java.lang.String _buscaOpcoes__return = port.buscaOpcoes(_buscaOpcoes_listaObjetos, _buscaOpcoes_tipoResultado, _buscaOpcoes_usuario, _buscaOpcoes_senha);
            System.out.println("buscaOpcoes.result=" + _buscaOpcoes__return);

        } catch (SigepClienteException e) {
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
